import axios from "axios";

const rootUrl = 'https://react-native-course-292f4-default-rtdb.firebaseio.com/';

export const storeExpense = async (expenseData) => {
    const res = await axios.post(
        rootUrl + '/expenses.json',
        expenseData
    );
    return res.data.name; // return ID generated by firebase
}

export const fetchExpenses = async () => {
    const res = await axios.get(rootUrl + '/expenses.json');
    const expenses = [];

    for (const key in res.data) {
        const expenseObj = {
            id: key,
            amount: res.data[key].amount,
            date: new Date(res.data[key].date),
            description: res.data[key].description
        }
        expenses.push(expenseObj)
    }

    return expenses;
}

export const updateExpense = (id, expenseData) => {
    return axios.put(rootUrl + `/expenses/${id}.json`, expenseData);
}

export const deleteExpense = (id) => {
    return axios.delete(rootUrl + `expenses/${id}.json`);
}